# Generated by Django 4.1.2 on 2022-10-26 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('n_orden', models.UUIDField()),
                ('numero_de_factura', models.PositiveIntegerField()),
                ('tipo_de_pago', models.CharField(choices=[('RG', 'Registrado'), ('NRG', 'No Registrado')], max_length=3)),
                ('forma_de_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia'), ('CREDITO', 'Credito'), ('DEBITO', 'Debito')], max_length=32)),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.camion')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.empleado')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CompraProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordencompra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.producto')),
            ],
        ),
    ]
