# Generated by Django 4.1.2 on 2022-10-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_ordencompra_n_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='importe',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
